---
# name: jomrr.ansible-role-nfs
# file: molecule/all/molecule.yml

dependency:
  name: galaxy
  requirements-file: meta/requirements.yml
  role-file: meta/requirements.yml
driver:
  name: podman
lint: set -e; ansible-lint
provisioner:
  config_options:
    defaults:
      callback_whitelist: profile_tasks, timer, yaml
      interpreter_python: auto_silent
    ssh_connection:
      pipelining: true
  inventory:
    group_vars:
      all:
        nfs_client: true
        nfs_exports: {}
        nfs_server: true
  log: true
  name: ansible
  playbooks:
    converge: ../resources/converge.yml
    verify: ../resources/verify.yml
scenario:
  name: all
verifier:
  name: ansible
platforms:
  - name: almalinux-8-nfs
    image: "docker.io/jomrr/molecule-almalinux:8"
    pre_build_image: true
    entrypoint: null
    command: null
    systemd: true
  - name: almalinux-9-nfs
    image: "docker.io/jomrr/molecule-almalinux:9"
    pre_build_image: true
    entrypoint: null
    command: null
    systemd: true
  - name: alpine-3.18-nfs
    image: "docker.io/jomrr/molecule-alpine:3.18"
    pre_build_image: true
    entrypoint: null
    command: null
    systemd: true
  - name: alpine-3.19-nfs
    image: "docker.io/jomrr/molecule-alpine:3.19"
    pre_build_image: true
    entrypoint: null
    command: null
    systemd: true
  - name: debian-11-nfs
    image: "docker.io/jomrr/molecule-debian:11"
    pre_build_image: true
    entrypoint: null
    command: null
    systemd: true
  - name: debian-12-nfs
    image: "docker.io/jomrr/molecule-debian:12"
    pre_build_image: true
    entrypoint: null
    command: null
    systemd: true
  - name: fedora-39-nfs
    image: "docker.io/jomrr/molecule-fedora:39"
    pre_build_image: true
    entrypoint: null
    command: null
    systemd: true
  - name: fedora-40-nfs
    image: "docker.io/jomrr/molecule-fedora:40"
    pre_build_image: true
    entrypoint: null
    command: null
    systemd: true
  - name: fedora-rawhide-nfs
    image: "docker.io/jomrr/molecule-fedora:rawhide"
    pre_build_image: true
    entrypoint: null
    command: null
    systemd: true
  - name: ubuntu-20.04-nfs
    image: "docker.io/jomrr/molecule-ubuntu:20.04"
    pre_build_image: true
    entrypoint: null
    command: null
    systemd: true
  - name: ubuntu-22.04-nfs
    image: "docker.io/jomrr/molecule-ubuntu:22.04"
    pre_build_image: true
    entrypoint: null
    command: null
    systemd: true
  - name: ubuntu-24.04-nfs
    image: "docker.io/jomrr/molecule-ubuntu:24.04"
    pre_build_image: true
    entrypoint: null
    command: null
    systemd: true
