---
# name: jomrr.ansible-role-nfs
# file: molecule/default/molecule.yml

dependency:
  name: galaxy
  requirements-file: meta/requirements.yml
  role-file: meta/requirements.yml
driver:
  name: podman
lint: set -e; ansible-lint
platforms:
  - command: null
    entrypoint: null
    image: docker.io/${uns:-jomrr}/molecule-${img:-fedora}:${tag:-latest}
    name: nfs
    pre_build_image: true
    systemd: true
provisioner:
  config_options:
    defaults:
      callback_whitelist: profile_tasks, timer, yaml
      interpreter_python: auto_silent
    ssh_connection:
      pipelining: true
  inventory:
    group_vars:
      all:
        nfs_client: true
        nfs_exports: {}
        nfs_server: true
  log: true
  name: ansible
  playbooks:
    converge: ../resources/converge.yml
    verify: ../resources/verify.yml
scenario:
  name: default
verifier:
  name: ansible
