---
# role: nfs
# file: molecule/dev/molecule.yml

dependency:
  name: "galaxy"
  options:
    requirements-file: "${MOLECULE_PROJECT_DIRECTORY}/collections.yml"
    role-file: "${MOLECULE_PROJECT_DIRECTORY}/collections.yml"
driver:
  name: "podman"
provisioner:
  name: "ansible"
  config_options:
    defaults:
      forks: 8
      interpreter_python: "auto_silent"
      allow_world_readable_tmpfiles: true
      callbacks_enabled: "ansible.builtin.default"
      callback_result_format: "yaml"
      remote_tmp: "/tmp/.ansible/tmp"
    ssh_connection:
      pipelining: true
  log: true
  playbooks:
    converge: "../resources/playbooks/converge.yml"
    verify: "../resources/playbooks/verify.yml"
    prepare: "../resources/playbooks/prepare.yml"
    side_effect: "../resources/playbooks/side_effect.yml"
  connection_options:
    ansible_user: "molecule"
  inventory:
    group_vars:
      all:
        nfs_realm: "NFS.TEST"
        nfs_host_fqdn: "{{ inventory_hostname }}.nfs.test"
        __nfs_test_admin_password: "Molecule-Only-Adm1n!"
        __nfs_test_user_password: "Molecule-Only-Us3r!"
      nfs_test_servers:
        nfs_server: true
        nfs_client: false
        nfs_exports:
          /srv/nfs/projects:
            group: "nfs-users"
            mode: "2770"
            hosts:
              '*':
                - "rw"
    host_vars:
      nfs-client:
        nfs_server: false
        nfs_client: true
        nfs_mounts:
          /mnt/nfs-alma:
            src: "nfs-alma.nfs.test:/srv/nfs/projects"
          /mnt/nfs-debian:
            src: "nfs-debian.nfs.test:/srv/nfs/projects"
          /mnt/nfs-fedora:
            src: "nfs-fedora.nfs.test:/srv/nfs/projects"
          /mnt/nfs-leap:
            src: "nfs-leap.nfs.test:/srv/nfs/projects"
          /mnt/nfs-suse:
            src: "nfs-suse.nfs.test:/srv/nfs/projects"
          /mnt/nfs-ubuntu:
            src: "nfs-ubuntu.nfs.test:/srv/nfs/projects"
verifier:
  name: "ansible"
scenario:
  test_sequence:
    - "dependency"
    - "destroy"
    - "syntax"
    - "create"
    - "prepare"
    - "converge"
    - "idempotence"
    - "check"
    - "verify"
    - "side_effect"
    - "converge"
    - "idempotence"
    - "verify"
    - "destroy"
  name: "dev"
platforms:
  - name: "nfs-dc"
    hostname: "nfs-dc.nfs.test"
    image: "docker.io/jomrr/molecule-debian:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
    privileged: true
    network: "nfs-${MOLECULE_SCENARIO_NAME}"
    groups:
      - "nfs_test_dc"
  - name: "nfs-alma"
    hostname: "nfs-alma.nfs.test"
    image: "docker.io/jomrr/molecule-almalinux:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
    privileged: true
    network: "nfs-${MOLECULE_SCENARIO_NAME}"
    groups:
      - "nfs_test_servers"
  - name: "nfs-debian"
    hostname: "nfs-debian.nfs.test"
    image: "docker.io/jomrr/molecule-debian:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
    privileged: true
    network: "nfs-${MOLECULE_SCENARIO_NAME}"
    groups:
      - "nfs_test_servers"
  - name: "nfs-fedora"
    hostname: "nfs-fedora.nfs.test"
    image: "docker.io/jomrr/molecule-fedora:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
    privileged: true
    network: "nfs-${MOLECULE_SCENARIO_NAME}"
    groups:
      - "nfs_test_servers"
  - name: "nfs-leap"
    hostname: "nfs-leap.nfs.test"
    image: "docker.io/jomrr/molecule-opensuse-leap:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
    privileged: true
    network: "nfs-${MOLECULE_SCENARIO_NAME}"
    groups:
      - "nfs_test_servers"
  - name: "nfs-suse"
    hostname: "nfs-suse.nfs.test"
    image: "docker.io/jomrr/molecule-opensuse-tumbleweed:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
    privileged: true
    network: "nfs-${MOLECULE_SCENARIO_NAME}"
    groups:
      - "nfs_test_servers"
  - name: "nfs-ubuntu"
    hostname: "nfs-ubuntu.nfs.test"
    image: "docker.io/jomrr/molecule-ubuntu:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
    privileged: true
    network: "nfs-${MOLECULE_SCENARIO_NAME}"
    groups:
      - "nfs_test_servers"
  - name: "nfs-client"
    hostname: "nfs-client.nfs.test"
    image: "docker.io/jomrr/molecule-debian:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
    privileged: true
    network: "nfs-${MOLECULE_SCENARIO_NAME}"
    groups:
      - "nfs_test_clients"
