---
# role: nfs
# file: molecule/resources/playbooks/converge.yml

- name: NFS | Configure servers before clients
  hosts: nfs_test_servers
  gather_facts: true
  roles:
    - role: '{{ lookup("ansible.builtin.env", "MOLECULE_PROJECT_DIRECTORY") }}'

- name: NFS | Configure client mounts
  hosts: nfs_test_clients
  gather_facts: true
  roles:
    - role: '{{ lookup("ansible.builtin.env", "MOLECULE_PROJECT_DIRECTORY") }}'
